name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.DIOUSERSCRUD_AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.DIOUSERSCRUD_AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.DIOUSERSCRUD_AZURE_SUBSCRIPTION_ID }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}/src
        acrName: diouserscrud
        containerAppName: dio-userscrud
        resourceGroup: DIO-PublishAPI

    # - name: Setup JDK 17
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '17's
    #     distribution: 'temurin'
    #     cache: maven
    # - name: Build w/ Maven
    #   run: mvn -B package --file pom.xml
